/*
    config.h - DO NOT EDIT THIS FILE, change what you need in config_override.h
    See config_override_example.h
*/
#define USE_CONFIG_OVERRIDE 


#define SERIAL_DEBUG true
#define OTA_KEY ""


/************************************************************/
/*****                     WiFi                        ******/
/************************************************************/
#define IP            {0,0,0,0}
#define GATEWAY       {0,0,0,0}
#define NETWORK_MASK  {0,0,0,0}

#define WIFI_SSID       "SSID"
#define WIFI_PASSWORD   "PASSWORD"
#define HOST_NAME       "NixieClock"


/************************************************************/
/*****                     MQTT                        ******/
/************************************************************/

#define MQTT_SERVER      ""
#define MQTT_SERVERPORT  1883                   // 8883 for MQTTS
#define MQTT_USERNAME    ""
#define MQTT_KEY         ""
#define MQTT_FINGERPRINT ""
#define MQTT_TOPIC       ""

//#define MQTT_CONN_KEEPALIVE 10

/************************************************************/
/*****                     PINS                        ******/
/************************************************************/
#define NUM_CHIPS 4

#define LATCH_PIN D2
#define CLOCK_PIN D1
#define DATA_PIN D0

/************************************************************/
/*****                 Clock options                   ******/
/************************************************************/

#define TIMEZONE 1
#define TIME_HOST "pool.ntp.org"
#define INTERVAL_NTP 20*60*1000
#define USE_DST true

#define SHOW_DATE true 
#if SHOW_DATE
  #define DATE_START_SECOND 40
  #define DATE_DISPLAY_TIME 10
#endif

#define SHOW_TEMP false 
#if SHOW_TEMP
  #define TEMP_START_SECOND 50
  #define TEMP_DISPLAY_TIME 10
#endif

#define CYCLE_LAMPS true
#if CYCLE_LAMPS
  #define CYCLE_START_SECOND 0
  #define CYCLE_TIME 1
#endif

#ifdef USE_CONFIG_OVERRIDE
  #if __has_include(<config_override.h>)
    #include <config_override.h>         // Configuration overrides for user_config.h
  #endif
#endif