/*
    config.h - DO NOT EDIT THIS FILE, change what you need in config_override.h
    See config_override_example.h
*/
#define USE_CONFIG_OVERRIDE 


#define SERIAL_DEBUG true
#define OTA_KEY ""


/************************************************************/
/*****                     WiFi                        ******/
/************************************************************/
#define IP            {0,0,0,0}
#define GATEWAY       {0,0,0,0}
#define NETWORK_MASK  {0,0,0,0}

#define WIFI_SSID       "SSID"
#define WIFI_PASSWORD   "PASSWORD"
#define HOST_NAME       "NixieClock"


/************************************************************/
/*****                     MQTT                        ******/
/************************************************************/

#define MQTT_SERVER      ""
#define MQTT_SERVERPORT  1883                   // 8883 for MQTTS
#define MQTT_USERNAME    ""
#define MQTT_KEY         ""
#define MQTT_FINGERPRINT ""
#define MQTT_TOPIC       ""

//#define MQTT_CONN_KEEPALIVE 10

/************************************************************/
/*****                     PINS                        ******/
/************************************************************/
#define NUM_CHIPS 4

#define LATCH_PIN D2
#define CLOCK_PIN D1
#define DATA_PIN D0

/************************************************************/
/*****                 Clock options                   ******/
/************************************************************/
#define TIMEZONE               +60  //Timezone offset from UTC in minutes

// -- Time - Start Daylight Saving Time and timezone offset from UTC in minutes
#define TIME_DST_HEMISPHERE    0             // [TimeDst] Hemisphere (0 -> North, 1 -> South)
#define TIME_DST_WEEK          0              // Week of month (0 -> Last, 1 -> First, 2 -> Second, 3 -> Third, 4 -> Fourth)
#define TIME_DST_DAY           1               // Day of week (1 -> Sun, 2 -> Mon, 3 -> Tue, 4 -> Wed, 5 -> Thu, 6 -> Fri, 7 -> Sat)
#define TIME_DST_MONTH         3               // Month (1 -> Jan, 2 -> Feb, 3 -> Mar, 4 -> Apr, 5 -> May, 6 -> Jun, 7 -> Jul, 8 -> Aug, 9 -> Sep, 10 -> Oct, 11 -> Nov, 12 -> Dec)
#define TIME_DST_HOUR          2                 // Hour (0 to 23)
#define TIME_DST_OFFSET        +60              // Offset from UTC in minutes (-780 to +780)

// -- Time - Start Standard Time and timezone offset from UTC in minutes
#define TIME_STD_HEMISPHERE    0             // [TimeStd] Hemisphere (0 -> North, 1 -> South)
#define TIME_STD_WEEK          0              // Week of month (0 -> Last, 1 -> First, 2 -> Second, 3 -> Third, 4 -> Fourth)
#define TIME_STD_DAY           1               // Day of week (1 -> Sun, 2 -> Mon, 3 -> Tue, 4 -> Wed, 5 -> Thu, 6 -> Fri, 7 -> Sat)
#define TIME_STD_MONTH         10               // Month (1 -> Jan, 2 -> Feb, 3 -> Mar, 4 -> Apr, 5 -> May, 6 -> Jun, 7 -> Jul, 8 -> Aug, 9 -> Sep, 10 -> Oct, 11 -> Nov, 12 -> Dec)
#define TIME_STD_HOUR          3                 // Hour (0 to 23)
#define TIME_STD_OFFSET        +0               // Offset from UTC in minutes (-780 to +780)

#define TIME_HOST "pool.ntp.org"
#define INTERVAL_NTP 20*60*1000
#define USE_DST true

#define SHOW_DATE true 
#if SHOW_DATE
  #define DATE_START_SECOND 40
  #define DATE_DISPLAY_TIME 10
#endif

#define SHOW_TEMP false 
#if SHOW_TEMP
  #define TEMP_START_SECOND 50
  #define TEMP_DISPLAY_TIME 10
#endif

#define CYCLE_LAMPS true
#if CYCLE_LAMPS
  #define CYCLE_START_SECOND 0
  #define CYCLE_TIME 1
#endif

#ifdef USE_CONFIG_OVERRIDE
  #if __has_include(<config_override.h>)
    #include <config_override.h>         // Configuration overrides for user_config.h
  #endif
#endif