#ifndef CONFIG_H
#define CONFIG_H
/*
    config.h - DO NOT EDIT THIS FILE, change what you need in config_override.h
    See config_override_example.h
*/
#define USE_CONFIG_OVERRIDE 


#define SERIAL_DEBUG true
#define OTA_KEY ""


/************************************************************/
/*****                     WiFi                        ******/
/************************************************************/
#define IP            {0,0,0,0}
#define GATEWAY       {0,0,0,0}
#define NETWORK_MASK  {0,0,0,0}

#define WIFI_SSID       "SSID"
#define WIFI_PASSWORD   "PASSWORD"
#define HOST_NAME       "NixieClock"


/************************************************************/
/*****                     MQTT                        ******/
/************************************************************/

#define MQTT_SERVER      ""
#define MQTT_SERVERPORT  1883                   // 8883 for MQTTS
#define MQTT_USERNAME    ""
#define MQTT_KEY         ""
#define MQTT_FINGERPRINT ""
#define MQTT_TOPIC       ""

//#define MQTT_CONN_KEEPALIVE 10

/************************************************************/
/*****                     PINS                        ******/
/************************************************************/

#define LATCH_PIN D2
#define CLOCK_PIN D1
#define DATA_PIN D0

/************************************************************/
/*****                 Clock options                   ******/
/************************************************************/
#define TIMEZONE               1*60 //Timezone offset from UTC in minutes

// -- Time - Start Daylight Saving Time and timezone offset from UTC in minutes
#define TIME_DST_WEEK          Last              // Week of month (0 or Last, 1 or First, 2 or Second, 3 or Third, 4 or Fourth)
#define TIME_DST_DAY           Sun               // Day of week (1 or Sun, 2 or Mon, 3 or Tue, 4 or Wed, 5 or Thu, 6 or Fri, 7 or Sat)
#define TIME_DST_MONTH         Mar               // Month (1 or Jan, 2 or Feb, 3 or Mar, 4 or Apr, 5 or May, 6 or Jun, 7 or Jul, 8 or Aug, 9 or Sep, 10 or Oct, 11 or Nov, 12 or Dec)
#define TIME_DST_HOUR          2                 // Hour (0 to 23)
#define TIME_DST_OFFSET        1*60              // Offset from UTC in minutes

// -- Time - Start Standard Time and timezone offset from UTC in minutes
#define TIME_STD_WEEK          Last              // Week of month (0 or Last, 1 or First, 2 or Second, 3 or Third, 4 or Fourth)
#define TIME_STD_DAY           Sun               // Day of week (1 or Sun, 2 or Mon, 3 or Tue, 4 or Wed, 5 or Thu, 6 or Fri, 7 or Sat)
#define TIME_STD_MONTH         Oct               // Month (1 or Jan, 2 or Feb, 3 or Mar, 4 or Apr, 5 or May, 6 or Jun, 7 or Jul, 8 or Aug, 9 or Sep, 10 or Oct, 11 or Nov, 12 or Dec)
#define TIME_STD_HOUR          3                 // Hour (0 to 23)
#define TIME_STD_OFFSET        0*60              // Offset from UTC in minutes

#define TIME_HOST "pool.ntp.org"
#define INTERVAL_NTP 20*60*1000
#define USE_DST true

#define SHOW_DATE true 
#if SHOW_DATE
  #define DATE_START_SECOND 40
  #define DATE_DISPLAY_TIME 10
#endif

#define SHOW_TEMP false 
#if SHOW_TEMP
  #define TEMP_START_SECOND 50
  #define TEMP_DISPLAY_TIME 10
#endif

#define CYCLE_LAMPS true
#if CYCLE_LAMPS
  #define CYCLE_START_SECOND 0
  #define CYCLE_TIME 1
#endif

#ifdef USE_CONFIG_OVERRIDE
    #include <config_override.h>         // Configuration overrides for user_config.h
#endif
#endif