name: Test Configuration
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy config overrides file
        run: cp src/config_override_example.h src/config_override.h
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run
